services:
    application:
        build:
            context: "."
            dockerfile: "docker/application/application.dockerfile"
        depends_on:
            -   database
        environment:
            DATABASE_HOST: database
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_PORT: ${DATABASE_PORT}
        ports:
            - "8080:8080"
        restart: "on-failure"
    application-tester:
        build:
            context: "."
            dockerfile: "docker/application-tester/application-tester.dockerfile"
        depends_on:
            -   application
    database:
        build:
            context: "."
            dockerfile: "docker/database/database.dockerfile"
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        restart: "on-failure"