services:
    application:
        build:
            context: "."
            dockerfile: "docker/application/application.dockerfile"
        ports:
            - "8080:8080"
        restart: "always"