services:
    application:
        build:
            context: "."
            dockerfile: "docker/application/application.dockerfile"
        ports:
            - "8080:8080"
        restart: "on-failure"
    application-tester:
        build:
            context: "."
            dockerfile: "docker/application-tester/application-tester.dockerfile"
        depends_on:
            -   application